package com.dongkun.dao;

import com.dongkun.entity.Employment;
import com.dongkun.entity.EmploymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    long countByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int deleteByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int insert(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int insertSelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    List<Employment> selectByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    Employment selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employment record, @Param("example") EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int updateByExample(@Param("record") Employment record, @Param("example") EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int updateByPrimaryKeySelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Wed May 08 08:00:33 CST 2019
     */
    int updateByPrimaryKey(Employment record);
}